import { createContext, useContext, useState } from 'react'

const LanguageContext = createContext({ lang: 'en', toggleLang: () => {} })

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    try { return localStorage.getItem('imove_lang') ?? 'en' } catch { return 'en' }
  })

  const toggleLang = () => {
    const next = lang === 'en' ? 'vi' : 'en'
    setLang(next)
    try { localStorage.setItem('imove_lang', next) } catch {}
  }

  return (
    <LanguageContext.Provider value={{ lang, toggleLang }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLang() {
  return useContext(LanguageContext)
}

/** Returns a t(key, ...args) function scoped to the current language. */
export function useT() {
  const { lang } = useLang()
  function t(key, ...args) {
    const T = lang === 'vi' ? VI : EN
    const val = T[key]
    if (val === undefined) return key
    if (typeof val === 'function') return val(...args)
    return val
  }
  return { t, lang }
}

/* ── Translations ─────────────────────────────────────────────────── */

const EN = {
  /* ── Header ──────────────────────── */
  home: 'Home',
  newTrip: 'New Trip',
  signIn: 'Sign In',
  signOut: 'Sign out',
  setting: 'Setting',
  language: 'Language',

  /* ── Auth modal ───────────────────── */
  signInTitle: 'Sign in',
  signUpTitle: 'Create account',
  signInDesc: 'Save your trips and access them anytime',
  signUpDesc: 'Create a free account to save and manage your trips',
  emailLabel: 'Email',
  passwordLabel: 'Password',
  passwordHint: '(min. 6 characters)',
  displayNameLabel: 'Display name',
  displayNamePlaceholder: 'Your name',
  processingBtn: 'Processing…',
  signInBtn: 'Sign in',
  createAccountBtn: 'Create account',
  noAccount: "Don't have an account? Sign up",
  alreadyAccount: 'Already have an account? Sign in',
  continueWithout: 'Continue without signing in',
  checkEmailTitle: 'Check your email',
  checkEmailDesc: (email) =>
    `We sent a confirmation link to ${email}. Click it to activate your account, then sign in.`,
  closeBtn: 'Close',
  passwordTab: 'Password',
  magicLinkTab: 'Magic Link',
  sendMagicLinkBtn: 'Send magic link',
  signInWithGoogle: 'Sign in with Google',

  /* ── Home ────────────────────────── */
  yourItineraries: 'Your itineraries',
  welcomeBack: 'Welcome back',
  welcomeUser: (name) => `Welcome back, ${name}!`,
  tripsCount: (n) => `${n} trip${n !== 1 ? 's' : ''} saved`,
  happeningToday: (n) => `${n} happening today`,
  upcomingCount: (n) => `${n} upcoming`,
  createNewItinerary: 'Create New Itinerary',
  imoveRoute: 'IMOVE Route',
  liveToday: 'Live today',
  readyLabel: 'Ready',
  nextItinerary: 'Next itinerary',
  singaporePlanner: 'Singapore planner',
  homeStatTrips: 'Trips',
  homeStatToday: 'Today',
  homeStatUpcoming: 'Upcoming',
  travelWorkspace: 'Travel workspace',
  travelWorkspaceDesc: 'Plan, reopen, and continue your saved IMOVE itineraries.',
  previewLabel: 'Preview',
  previewMeta: '3 days · 8 stops · transit ready',
  routePointAirport: 'Airport',
  routePointMrt: 'MRT Blue Line',
  routePointMarina: 'Marina Bay',
  landingHeroEyebrow: 'Singapore public transport planner',
  landingHeroLine1: 'Transit Planning Made',
  landingHeroEasy: 'Easy',
  landingHeroDesc:
    'IMOVE helps first-time Singapore travelers turn a list of places into a day-by-day itinerary with verified MRT, bus, walking time, cost, and live disruption support.',
  landingHeroCta: 'Start transit planning',
  landingHeroStatLive: 'live transit checks',
  landingHeroStatAgents: 'planning agents',
  landingHeroStatFake: 'estimated routes',
  landingSavedEyebrow: 'Your workspace',
  landingSavedTitle: 'Continue your saved itineraries',
  landingInnovativeEyebrow: 'Innovative transit planning',
  landingInnovativeTitle: 'Built for tourists who need more than a static map',
  landingFeatureRoutingTitle: 'Verified MRT and bus routes',
  landingFeatureRoutingDesc:
    'Every leg is planned with real public transport routing data instead of guessed travel times.',
  landingFeatureAlertsTitle: 'Realtime disruption awareness',
  landingFeatureAlertsDesc:
    'IMOVE watches for MRT, bus, weather, and service issues that can affect today’s itinerary.',
  landingFeatureAgentsTitle: 'Adaptive multi-agent planning',
  landingFeatureAgentsDesc:
    'Planning, adaptation, and memory agents work together to suggest practical route changes.',
  landingStepsEyebrow: 'Book easy 3 steps',
  landingStepsTitle: 'Create a Singapore itinerary that already knows how you will move',
  landingStepPlacesTitle: 'Choose your places',
  landingStepPlacesDesc:
    'Add attractions, food spots, and neighborhoods you want to visit across one or more days.',
  landingStepPlanTitle: 'Generate transport-aware days',
  landingStepPlanDesc:
    'IMOVE orders stops and attaches MRT, bus, walking time, cost, and route details to each leg.',
  landingStepAdaptTitle: 'Navigate and adapt',
  landingStepAdaptDesc:
    'When a line delay, weather change, or route issue appears, the app can propose a safer swap.',
  landingServicesEyebrow: 'IMOVE best services',
  landingServicesTitle: 'Public transport support from planning to trip day',
  landingServiceRail: 'Rail routing',
  landingServiceBus: 'Bus options',
  landingServiceLive: 'Active alerts',
  landingServiceVerified: 'No fake fallback',
  landingDiscoverEyebrow: 'Discover our features',
  landingDiscoverTitle: 'Designed around Singapore transit realities',
  landingDiscoverMapTitle: 'Map-linked itinerary',
  landingDiscoverMapDesc:
    'Review every day beside route lines, stops, and transport mode markers.',
  landingDiscoverWeatherTitle: 'Weather-aware replanning',
  landingDiscoverWeatherDesc:
    'Outdoor-heavy plans can be adjusted when forecast or rain risk changes.',
  landingDiscoverBudgetTitle: 'Fare and walking context',
  landingDiscoverBudgetDesc:
    'See cost, active time, and walking distance before committing to a route.',
  landingDiscoverMemoryTitle: 'Learns from feedback',
  landingDiscoverMemoryDesc:
    'Saved feedback helps future plans better match your transport preferences.',
  landingReadyEyebrow: 'Ready for your Singapore trip plan',
  landingReadyTitle: 'Plan confidently even if you do not know MRT, bus, or local geography',
  landingReadyDesc:
    'Start with places you care about. IMOVE turns them into a transport-first itinerary and keeps the plan flexible when the real world changes.',
  landingReadyCardTitle: 'Solo and small-group friendly',
  landingReadyCardDesc:
    'Best for travelers visiting Singapore for the first time or anyone who wants a clearer transit plan.',
  landingFooterDesc:
    'IMOVE is a transport-first travel planner for Singapore, combining itinerary planning with realtime public transport adaptation.',
  landingFooterExplore: 'Explore',
  landingFooterPlanner: 'Planner',
  landingFooterTrips: 'Saved trips',
  landingFooterAlerts: 'Transit alerts',
  landingFooterSupport: 'Support',
  landingFooterContact: 'Contact',
  landingFooterMessage: 'Send a message',
  landingContactName: 'Name',
  landingContactEmail: 'Email',
  landingContactMessage: 'How can we help?',
  landingContactSend: 'Send',
  filter_All: 'All',
  filter_Today: 'Today',
  filter_Upcoming: 'Upcoming',
  filter_Drafts: 'Drafts',
  filter_Past: 'Past',
  noTripsTitle: 'Plan your Singapore adventure',
  noTripsDesc: 'Create your first trip with real MRT and bus routes, timed itineraries, and AI-powered suggestions.',
  startPlanning: 'Start Planning',
  planNewTrip: 'Plan a new trip',
  freshItinerary: 'Start a fresh itinerary',
  openBtn: 'Open',
  startTripBtn: 'Start Trip',
  liveLabel: 'Live',
  startsTodayTitle: 'Your trip to Singapore starts today!',
  startsTodayDesc: "Ready to explore? We'll navigate you through your itinerary.",
  laterBtn: 'Later',
  readyToNavigate: 'Ready to navigate',
  noTripsCategory: 'No trips in this category yet.',
  dest: 'Dest.',
  savedLabel: 'Saved',
  daysUnit: (n) => `${n} day${n !== 1 ? 's' : ''}`,
  stopsUnit: (n) => `${n} stop${n !== 1 ? 's' : ''}`,

  /* ── Planner — mode chooser ────────── */
  planYourTrip: 'Plan your Singapore trip',
  choosePlanMethod: 'Choose how to create your itinerary',
  buildYourselfTitle: 'Build it yourself',
  buildYourselfDesc:
    'Choose each place you want to visit — the system suggests transport between stops and you can customise freely.',
  recommendedBadge: 'Recommended',
  tag_freeChoice: 'Free choice',
  tag_transport: 'Transport suggestions',
  tag_customizable: 'Customizable',
  planWithAITitle: 'Plan with AI',
  planWithAIDesc:
    "Enter your preferences and let AI suggest an itinerary. Great when you're not sure where to go.",
  changeMethod: 'Change method',

  /* ── Planner — manual ──────────────── */
  manualHeaderLabel: 'Build your own itinerary',
  manualHeaderSub: 'Add places and choose transport between them',
  tripInfoSection: 'Trip info',
  tripNameLabel: 'Trip name',
  tripNamePlaceholder: 'E.g. Singapore 4D3N Adventure',
  flexibleLabel: 'Flexible',
  specificDatesLabel: 'Specific dates',
  flexibleHint: 'Flexible dates — set them later from the trip page.',
  numDaysLabel: 'Duration',
  placesSection: (n) => `Places (${n})`,
  clickToChange: 'Click a badge to change transport',
  noPlacesTitle: 'No places added yet',
  noPlacesHint: 'Click "Add place" below to get started',
  addPlaceBtn: 'Add place',
  searchPlaceTitle: 'Search & add a place',
  createTripBtn: (n) => `Create Itinerary (${n} place${n !== 1 ? 's' : ''})`,
  addAtLeastOne: 'Add at least 1 place to continue',
  creatingTrip: 'Creating your trip…',

  /* ── Planner — AI ──────────────────── */
  aiHeaderLabel: 'AI Planning',
  aiHeaderSub: 'AI will suggest an itinerary based on your preferences',
  whenGoingLabel: 'When are you going?',
  flexibleDatesHint: 'Flexible dates — set them later from the trip page.',
  preferencesLabel: 'Preferences',
  travellingWithLabel: 'Travelling with',
  travelStyleLabel: 'Travel style',
  tripPaceLabel: 'Trip pace',
  aiHint:
    "We'll curate the best places for you based on your travel style and pace, then build a full day-by-day itinerary with real MRT and bus routes.",
  planWithAIBtn: 'Plan with AI',
  planningBtn: 'Planning your trip…',
  selectStartDate: 'Please select a start date to continue',

  /* ── Planner — confirm step ────────── */
  planReady: 'Plan ready!',
  saveItinerary: 'Save your itinerary?',
  startOver: 'Start Over',
  saveAndView: 'Save & View Itinerary',

  /* ── Place search ──────────────────── */
  popularPlaces: 'Popular places in Singapore',
  searchPlaceholder: 'Search places in Singapore…',
  addedBtn: 'Added',
  addBtn: 'Add',
  limitedData: 'Limited data',
  noResults: (q) => `No places found for "${q}"`,
  loadingPlaces: 'Loading places…',
  statusToday: 'Happening Today',
  or: 'or',
  flexibleDates: 'Flexible dates',

  /* ── Transport ─────────────────────── */
  transport_walk: 'Walk',
  transport_bus: 'Bus',
  transport_mrt: 'MRT',

  /* ── Alert Banner ────────────────── */
  alertTransit: 'Transit Alert',
  alertWeather: 'Weather Alert',
  alertService: 'Service Notice',
  alertPreview: 'Preview swap',
  alertAccept: 'Accept',
  alertAcceptSwap: 'Accept swap',
  alertDismiss: 'Dismiss',
  alertGotIt: 'Got it',
  alertUpdating: 'Updating...',
  alertApplying: 'Applying...',
  alertDiscard: 'Discard',
  alertPreviewExpired: 'This preview expired. Preview again to recalculate the adaptation.',
  alertHelpful: 'Helpful',
  alertNotHelpful: 'Not helpful',
  alertFeedbackSent: 'Feedback sent',
  alertFeedbackLoginRequired: 'Sign in to send feedback for this trip.',
  alertFeedbackFailed: 'Could not send feedback. Please try again.',
  alertRain: 'Rain',
  alertChance: (pct) => `${pct}% chance`,
  alertOutdoorAffected: (count) => `· ${count} outdoor stop${count !== 1 ? 's' : ''} affected`,
  alertOutdoorFallback: 'Weather may affect outdoor stops',
  alertNoSwapsNeeded: 'No swaps needed — all stops are indoor-friendly.',

  /* ── Closing-risk alert (dev20) ───── */
  alertSchedule: 'Running late',
  crHeader: (place, closeTime, arrival, deficit) =>
    `${place} closes at ${closeTime} — you're projected to arrive ${arrival} (~${deficit} min late).`,
  crLeaveEarlier: 'Leave earlier',
  crLeaveEarlierAdvice: (place, time, mins) =>
    `Leave ${place} before ${time} (~${mins} min earlier) and you'll still make it.`,
  crSkip: 'Skip this stop',
  crPush: 'Move to another day',
  crChooseDay: 'Choose a day:',
  crDayLabel: (day) => `Day ${day}`,
  crBadgeRoom: (mins) => `~${Math.round((mins / 60) * 10) / 10}h free`,
  crBadgeFull: 'Already full',
  crBadgeClosed: (weekday) => `Closed ${weekday}`,
  crPushClosedAll: (place) =>
    `Can't move to another day — ${place} is closed on every remaining day of your trip.`,
  crPushNoOtherDay: "Can't move — this is the last day, there's no other day to use.",
  crRecommended: 'Recommended',
  crConfirm: 'Confirm',

  /* ── Trip page ───────────────────── */
  tripDefaultName: 'Singapore Trip',
  tripDaysCount: (n) => `${n} day${n !== 1 ? 's' : ''}`,
  tripPlacesCount: (n) => `${n} place${n !== 1 ? 's' : ''}`,
  tripStopsCount: (n) => `${n} stop${n !== 1 ? 's' : ''}`,
  tripLive: 'Live',
  tripPaused: 'Paused',
  tripOverview: 'Overview',
  tripSummary: 'Summary',
  tripDay: (n) => `Day ${n}`,
  tripAddDay: 'Add day',
  tripRemoveDay: 'Remove day',
  tripEditSetup: 'Edit setup',
  tripResumeTrip: 'Resume trip',
  tripUpdateRoutesFirst: 'Update routes first',
  tripGoodToGo: 'Good to go',
  tripEstimated: 'Estimated',
  tripBannerLive: (day) => `Live · Day ${day} — tap Arrived when you reach each stop.`,
  tripBannerEdit: 'Edit mode — trip is paused. Resume when ready to navigate.',
  tripBannerPlanning: 'Planning mode — review your itinerary before you start.',
  tripGpsOff: 'GPS unavailable — auto-arrive is off. Tap Arrived manually at each stop.',
  tripStartsToday: 'Your trip starts today! Head to the dashboard to start.',
  tripOffline: 'Offline mode — showing your cached itinerary.',
  tripRainMore: (n) => `Rain forecast for ${n} more day${n !== 1 ? 's' : ''}`,
  tripLoadError: (msg) => `Could not load trip: ${msg}`,
  tripUnavailableTitle: 'Trip unavailable',
  tripUnavailableBody: () => 'We could not open this trip. It may be private, deleted, or you may not have permission to view it.',
  tripNotFound: 'Trip not found',
  tripAccessDenied: 'You do not have access to this trip.',
  tripLoginRequired: 'Please sign in again to view this trip.',
  tripBackHome: 'Back to home',
  tripStartNew: 'Start a new trip',
  tripOverviewDesc: 'Review warnings, free-time gaps, and your daily route structure.',
  tripUpdateRoute: 'Update route',
  tripKeepOrder: 'Keep my order',
  tripKeepOrderDesc: 'Real transit times, your stop order',
  tripLetAIOptimise: 'Let AI optimise',
  tripLetAIOptimiseDesc: 'AI reorders for the best efficiency',
  tripOptimiseOrder: 'Optimise order',
  tripStartTrip: 'Start trip',
  tripLongCommutes: 'Long commutes',
  tripDayDesc: 'Place and route cards with live transport details.',
  tripNoLegs: 'No route legs in this day',
  tripLongTransits: (n) => `${n} long transit${n > 1 ? 's' : ''} today`,
  tripTransit: 'transit',
  tripAddPlace: 'Add place',
  tripRemove: 'Remove',
  tripRemovePlace: 'Remove place',
  tripHotel: 'Hotel',
  tripReturnHotel: 'Return to hotel',
  tripUp: 'Up',
  tripDown: 'Down',
  tripEmptyDay: 'Empty day',
  tripEstimatedHint: 'Estimated — tap "Update route" to get real transit times.',
  tripDestination: 'Destination',
  tripStartingFrom: 'Starting from',
  tripMinVisit: (n) => `${n} min visit`,
  tripCategoryFallback: 'place',
  tripMinShort: (n) => `${n} min`,
  tripClosed: (days) => `Closed ${days}`,
  tripBestTime: (s, e) => `Best ${s}–${e}`,
  tripOrigin: 'Origin',
  tripRoute: (from, to) => `${from} → ${to}`,
  tripOpenGrab: 'Open Grab',
  tripChange: 'Change',
  tripComparing: 'Comparing…',
  tripCompareModes: 'Compare modes',
  tripTransitDetails: 'Transit details',
  tripUnavailable: 'Unavailable',
  tripBusLabel: (route, name) => `Bus ${route}${name ? ` — ${name}` : ''}`,
  tripYourLocation: 'Your location',
  tripGrabOpened: (from, to) => `Grab opened — pickup: ${from}, drop-off: ${to}`,
  tripGrabNotFound: (from, to) => `Grab app not found — opened Google Maps instead (${from} → ${to})`,
  tripActiveLeg: 'Active leg',
  tripLegProgress: (day, i, total) => `Day ${day} · Leg ${i} of ${total}`,
  tripBack: 'Back',
  tripGoBackTitle: 'Go back to the previous leg',
  tripContinue: 'Continue',
  tripArrived: 'Arrived',
  tripDeleteConfirm: 'Delete this trip permanently?',
  // dev28 — shared confirm dialog + date/time picker strings
  confirmDeleteTitle: 'Delete trip?',
  confirmDeleteBtn: 'Delete',
  cancelBtn: 'Cancel',
  drpNoDates: 'No dates selected',
  drpPickEnd: 'pick an end date',
  drpDayCount: (n) => `${n} ${n === 1 ? 'day' : 'days'}`,
  tripOptimiseTitle: 'Optimise order?',
  tripOptimiseDesc: 'AI will reorder your stops for efficiency using real transit data. Your current order may change.',
  tripCancel: 'Cancel',
  tripConfirm: 'Confirm',
  tripMsgEstimatedLegs: (n) => `Couldn't fetch real routes for ${n} leg${n !== 1 ? 's' : ''} — try Update route again shortly.`,
  tripMsgDistributed: (n) => `Route optimised — distributed across ${n} day${n !== 1 ? 's' : ''}.`,
  tripMsgReordered: (n) => `Route optimised! ${n} stop${n !== 1 ? 's' : ''} reordered.`,
  tripMsgRoutesUpdated: 'Routes updated with real transit times — itinerary unlocked.',
  tripMsgAlreadyOptimal: 'Already optimal — no reordering needed.',
  transport_cycle: 'Cycle',
  transport_grab: 'Grab',

  /* ── Summary tab ─────────────────── */
  sumSaveTitle: 'Save your itinerary',
  sumSaveDesc: 'Review your days and transport modes above, then save when ready.',
  sumTripName: 'Trip name',
  sumSaveBtn: 'Save itinerary',
  sumTitle: 'Trip summary',
  sumDesc: 'Estimates from your current itinerary — they recalculate when you change transport modes.',
  sumActiveTime: 'Active time',
  sumTransitCost: 'Transit cost',
  sumWalkDist: 'Walking distance',
  sumTransfers: 'Transfers',
  sumByDay: 'By day',
  sumPaceCheck: 'Pace check',
  sumPaceText: (stops, days, avg) => `Your trip has ${stops} stop${stops !== 1 ? 's' : ''} across ${days} day${days !== 1 ? 's' : ''} — averaging ${avg} stops/day. Looks comfortable.`,
  sumAgentActivity: 'Agent activity',
  sumNoAgent: 'No agent interventions recorded yet.',
  sumShareExport: 'Share & export',
  sumShareLink: 'Share link',
  sumSavePdf: 'Save as PDF',
  sumDanger: 'Danger zone',
  sumDangerDesc: 'Permanently removes this trip from the database.',
  sumDeleteTrip: 'Delete trip',

  /* ── Bus arrivals ────────────────── */
  busArr: 'Arr',
  busMin: (n) => `${n} min`,
  busRoute: 'Route',
  busArrivals: 'Arrivals',
  busLoad: 'Load',
  busLoadLow: 'Low',
  busLoadModerate: 'Moderate',
  busLoadHigh: 'High',
  busNoServices: 'No services found at this stop.',
  busRetry: 'Retry',
  busFailed: 'Failed to load arrivals',
  busJustNow: 'just now',
  busAgo: (s) => `${s}s ago`,
  busUpdated: (label) => `Updated ${label}`,
  busRefresh: 'Refresh arrivals',

  /* ── Settings page ───────────────── */
  setEyebrow: 'Settings',
  setTitle: 'Transport preferences',
  setDesc: 'IMOVE uses these priorities when choosing between MRT, bus, walking, and cycling alternatives.',
  setWFasterLabel: 'Faster routes',
  setWFasterDesc: 'Prefer shorter travel time',
  setWCostLabel: 'Lower fare',
  setWCostDesc: 'Prefer cheaper transit options',
  setWWalkLabel: 'Less walking',
  setWWalkDesc: 'Reduce walking distance',
  setWTransferLabel: 'Fewer transfers',
  setWTransferDesc: 'Avoid complicated routes',
  lvlLow: 'Low',
  lvlMed: 'Medium',
  lvlHigh: 'High',
  setSignInTitle: 'Sign in to curate your journey',
  setBullet1: 'Carry your travel plans seamlessly, across every device.',
  setBullet2: 'Discover routes sculpted around your unique pace and profile.',
  setBullet3: 'Chat with a smart assistant that plans and adapts your trip with ease.',
  setBullet4: 'Let “My Preferences” become your personal compass in the planner.',
  setRoutingPriorities: 'Routing priorities',
  setHowItWorks: 'How it works',
  setHowItWorksDesc: 'A higher level gives that factor stronger priority. Levels are balanced automatically when you save.',
  setReset: 'Reset',
  setSave: 'Save',
  setSaved: 'Preferences saved.',

  /* ── Home dashboard ──────────────── */
  homeBadge: 'IMOVE dashboard',
  homeHeroTitle: 'Plan, monitor, and adapt Singapore transport trips.',
  homeHeroDesc: 'Manage saved itineraries, start live trips, and prime LTA/weather checks before the route begins.',
  homeHeroCarouselTitle: 'Move through Singapore with a plan that keeps up.',
  homeHeroCarouselDesc: 'Build thoughtful itineraries, compare transport choices, and adapt your route as Singapore moves around you.',
  homeHeroCta: 'Plan a new trip',
  homeHeroSecondaryCta: 'Set preferences',
  homeFeature1Title: 'Plan around you',
  homeFeature1Desc: 'Balance time, cost, walking, and transfers.',
  homeFeature2Title: 'Build every day',
  homeFeature2Desc: 'Turn Singapore places into a practical route.',
  homeFeature3Title: 'Adapt while moving',
  homeFeature3Desc: 'Stay ready for live transport and weather changes.',
  homePreferences: 'Preferences',
  homeLive: 'Live',
  homeLtaWeather: 'LTA/weather',
  homeOpenAlerts: 'Open alerts',
  homeStatusToday: 'Today',
  homeStatusUpcoming: 'Upcoming',
  homeStatusDraft: 'Draft',
  homeStatusPast: 'Past',
  homeStartsTodaySuffix: 'starts today',
  homeStart: 'Start',
  homeDays: 'Days',
  homeStops: 'Stops',
  homeAlerts: 'Alerts',
  homeDeleteTitle: 'Delete trip',
  homeDeleteConfirm: (name) => `Delete "${name}"?`,
  homeSearch: 'Search saved trips',
  homeNoTrips: 'No trips here',
  homeNoTripsDesc: 'Create a new itinerary or change the filter.',

  /* ── Planner wizard ──────────────── */
  plnBackHome: 'Cancel and back to home',
  plnEyebrow: 'Itinerary Builder',
  plnTitle: 'Configure Singapore Trip',
  plnStep1: 'Essentials',
  plnStep2: 'Hotel Location',
  plnStep3: 'Travel Style',
  plnStep4: 'Sightseeing',
  plnGeneralSettings: 'General settings',
  plnGeneralDesc: 'Provide basic parameters to structure your itinerary.',
  plnTripName: 'Trip Name',
  plnBudget: 'Transit Budget (SGD)',
  plnDays: 'Days',
  plnDatesMode: 'Dates mode',
  plnFlexible: 'Flexible',
  plnCalendar: 'Calendar',
  plnStartDate: 'Start date',
  plnDailyStart: 'Daily Start Times',
  plnAutoOptimize: 'Auto-Optimize Order',
  plnAutoOptimizeDesc: 'Reorders places dynamically to save transit times.',
  plnHotelTitle: 'Hotel Accommodation',
  plnOptional: 'Optional',
  plnHotelDesc: "Provide where you stay. We start each day's route directly from your hotel.",
  plnHotelSearch: 'Hotel Search',
  plnHotelPlaceholder: 'e.g. Marina Bay Sands, Orchard Hotel',
  plnUse: 'Use',
  plnHotelNotFound: 'No location found. Try a more specific name.',
  plnTransitWeights: 'Transit weights',
  plnTransitDesc: 'Pick a travel profile to fine-tune how our routing ranks transport modes.',
  plnFastest: 'Fastest',
  plnFastestDesc: 'Minimizes travel duration. Prefers high-speed MRT lines.',
  plnCheapest: 'Cheapest',
  plnCheapestDesc: 'Minimizes fares. Prefers local bus lines and walk segments.',
  plnLeastWalking: 'Least Walking',
  plnLeastWalkingDesc: 'Hates walking. Selects door-to-door transit links.',
  plnLeastTransfers: 'Least Transfers',
  plnLeastTransfersDesc: 'Avoids line switches. Recommends single-board options.',
  plnUseProfile: 'Use My Preferences Profile',
  plnUseProfileDesc: 'Automatically loads your personalized scoring weights configured in user account settings.',
  plnWeightsAlloc: 'Scoring Weights Allocation',
  plnLoadsProfile: 'Loads account profile values from database',
  plnDimDuration: 'Travel Duration',
  plnDimCost: 'Fare Cost',
  plnDimWalking: 'Walking Minutes',
  plnDimTransfers: 'Number of Transfers',
  plnAttractions: 'Singapore attractions',
  plnStep4of4: 'Step 4 of 4',
  plnPickSights: 'Pick sights. Select at least 2 places from the curated list.',
  plnCuratedSearch: 'Curated POI Search',
  plnSelectedShortlist: (n) => `Selected Shortlist (${n})`,
  plnGenerating: 'Building',
  plnGeneratePlan: 'Generate',
  plnNextIdle: 'Next',
  plnNext: 'Next',
  plnConfigSummary: 'Trip Config Summary',
  plnDuration: 'Duration',
  plnSumBudget: 'Transit Budget',
  plnHotelStart: 'Hotel Start',
  plnTravelStyle: 'Travel Style',
  plnStopsSelected: 'Stops Selected',
  plnNotSet: 'Not Set',
  plnStartsFirstStop: 'Starts at first stop',
  plnMin2Places: 'Please select at least 2 places before generating a plan.',
  plnBackToTop: 'Back to top',
  plnNoSelected: 'No places selected yet',
  plnNoSelectedDesc: 'Select places on the left to add them to your trip.',
  plnDaysValue: (n) => `${n} Days`,
  plnStopsValue: (n) => `${n} stops`,

  /* ── DayPlan ─────────────────────── */
  dpNoStopsYet: 'No stops yet',
  dpDragReorder: 'Drag to reorder',
  dpNoPlaces: 'No places yet',
  dpNoPlacesDesc: 'Go back and add places to your itinerary.',
  dpAddPlaceToDay: (day) => `Add place to Day ${day}`,
  dpDayNotes: 'Day notes',
  dpDayNotesPlaceholder: 'Pack a light jacket, ATM stops, dinner reservation at 8pm…',

  /* ── Overview tab ────────────────── */
  ovOptimizing: 'Optimizing…',
  ovOptimizeRoute: 'Optimize Route',
  ovActive: 'Active',
  ovTransit: 'Transit',
  ovWalk: 'Walk',
  ovStops: 'Stops',
  ovViewMap: 'View on map',
  ovNotices: 'Notices',
  ovEmptyTap: 'Empty — tap to plan',

  /* ── Active leg focus ────────────── */
  alStopsCompleted: (n) => `${n} stop${n !== 1 ? 's' : ''} completed`,
  alStopsUpNext: (n) => `${n} stop${n !== 1 ? 's' : ''} up next`,
  alRainExpected: (name) => `Heavy rain expected at ${name}`,
  alSwapToPre: 'Swap to ',
  alSwapToPost: ' (indoor)?',
  alApproveSwap: 'Approve Swap ▶',
  alNoRoute: 'No route yet',
  alGetToStart: 'GET TO START',
  alArrivedAt: (name) => `Arrived at ${name}`,
  alToFirstStop: 'to first stop',
  alYouAreHere: 'YOU ARE HERE',
  alNear: (name) => `· near ${name}`,
  alAcquiringGps: 'Acquiring GPS location…',
  alDistTo: (dist, name) => `${dist} to ${name}`,
  alOpenRange: (s, e) => `Open · ${s} – ${e}`,
  alOutdoor: 'Outdoor',
  alMinVisit: (n) => `~${n} min visit`,
  alNotePlaceholder: 'Add a note for this stop…',
  alArrivedExcl: 'Arrived!',
  alArrivedDest: 'Arrived at Destination',

  /* ── Transit segment ─────────────── */
  tsChooseMode: 'Choose mode of transport',
  tsTransit: 'Transit',
  tsWalking: 'Walking',
  tsCycling: 'Cycling',
  tsNoRoute: 'No transit route available for this segment.',
  tsTaxiGrab: 'Taxi · Grab',
  tsOpenGrab: 'Open Grab app ↗',
  tsStraightLine: 'Straight-line distance',

  /* ── Citymapper transit card ─────── */
  ctLrt: 'LRT',
  ctDriveTaxi: 'Drive / Taxi',
  ctCrowdLow: 'Low',
  ctCrowdModerate: 'Moderate',
  ctWalkTo: (name, mins) => `Walk to ${name}${mins ? ` (${mins} min)` : ''}`,
  ctWalk: (mins) => `Walk${mins ? ` (${mins} min)` : ''}`,
  ctBoardAt: (name) => `Board at ${name}`,
  ctBoard: 'Board',
  ctAlightAt: (name) => ` → Alight at ${name}`,
  ctDur: (mins, stops) => ` (${mins} min${stops ? `, ${stops} stops` : ''})`,
  ctHide: 'Hide',
  ctLiveArrivals: 'Live arrivals',
  ctEstimatedNote: '~ Times are estimated based on typical route durations',
  ctLiveAlert: 'Live alert · Signal fault',
  ctDelayMsg: 'Delays up to 15 mins between Somerset and Bugis',
  ctAltRoute: 'Alternative route available',
  ctApproxMin: (n) => `~${n} min`,
  ctSaveMin: (n) => `Save ~${n} min`,
  ctSwitchBus: 'Switch to Bus Route ▶',
  ctDisrupted: 'DISRUPTED',
  ctEst: '~Est.',
  ctEditMode: 'Edit transport mode',

  /* ── Route card ──────────────────── */
  rcChangeMode: 'Change transport mode',
  rcNewMode: 'New mode',
  rcSaving: 'Saving...',

  /* ── Travel tips ─────────────────── */
  ttHeader: (n) => `Travel tips (${n})`,
  ttAlways1: 'Buy an EZ-Link card at Changi Airport or 7-Eleven for MRT/bus — easier than paying cash.',
  ttAlways2: 'Most hawker centres and street stalls are cash-only (SGD) — carry small notes.',
  ttOutdoor: 'Bring SPF 50+ sunscreen — Singapore has a high UV index year-round.',
  ttReligious: 'Dress modestly and remove your shoes before entering temples, mosques, or churches.',
  ttNight: 'Book tickets online in advance to skip queues at evening attractions.',
  ttNature: 'Check the forecast — afternoon showers are common from November to January.',

  /* ── Place card ──────────────────── */
  pcOpen24h: 'Open 24h',
  pcOpenHours: (s) => `Open ${s}`,
  pcOutdoor: 'Outdoor',
  pcBestTime: (label) => `Best time to visit: ${label}`,
  pcNotes: 'Notes',
  pcNotesPlaceholder: 'Add notes — book tickets in advance, bring jacket, etc.',

  /* ── Trip setup modal ────────────── */
  tsmTitle: 'Trip preferences',
  tsmDesc: 'Adjust trip name, dates, budget, hotel, and daily start time. Existing places stay in place.',
  tsmOriginPlaceholder: 'Ho Chi Minh City',
  tsmDates: 'Dates',
  tsmFlexibleDuration: 'Flexible duration',
  tsmStart: 'Start',
  tsmEnd: 'End',
  tsmDays: 'days',
  tsmDailyStart: 'Daily start time',
  tsmEachDay: 'each day',
  tsmHotel: 'Hotel',
  tsmHotelOptional: '(optional — daily start origin)',
  tsmHotelPlaceholder: 'e.g. Marina Bay Sands',
  tsmDateWarning: 'Changing dates, budget, hotel, or start time will re-run route planning. Existing places are kept; legs will be recalculated.',
  tsmSaveChanges: 'Save changes',

  /* ── Trip map ────────────────────── */
  tmEstimated: '(estimated)',
  tmCurrentLocation: 'Your current location',

  /* ── Chatbot ─────────────────────── */
  chatTitle: 'IMOVE Assistant',
  chatGreeting: "Hi! Ask me for place ideas or to tweak your itinerary — I'll suggest changes for you to confirm.",
  chatPlaceholder: 'Ask anything about your trip…',
  chatSend: 'Send',
  chatThinking: 'Thinking…',
  chatOpen: 'Open assistant',
  chatClose: 'Close assistant',
  chatProposalLabel: 'Proposed change',
  chatConfirm: 'Confirm',
  chatCancel: 'Cancel',
  chatApplying: 'Applying…',
  chatError: 'Something went wrong. Please try again.',
  chatLoginRequired: 'Sign in to use the assistant',
  chatLoginHint: 'The AI assistant is only available for logged-in users.',
  chatUnread: (n) => `${n} new trip update${n !== 1 ? 's' : ''}`,
  // dev25 P3 — rich chat blocks
  chatCardDuration: (n) => `${n} min`,
  chatRouteCompare: 'Route options',
  chatRouteFree: 'Free',
  chatMinShort: (n) => `${n} min`,
  chatBusArrivals: (stop) => `Bus stop ${stop}`,
  chatBusNow: 'Arriving',
  chatBusEta: (n) => `${n} min`,
  chatBusNone: 'No arrivals right now',
}

const VI = {
  /* ── Header ──────────────────────── */
  home: 'Trang chủ',
  newTrip: 'Chuyến mới',
  signIn: 'Đăng nhập',
  signOut: 'Đăng xuất',
  setting: 'Cài đặt',
  language: 'Ngôn ngữ',

  /* ── Auth modal ───────────────────── */
  signInTitle: 'Đăng nhập',
  signUpTitle: 'Tạo tài khoản',
  signInDesc: 'Lưu hành trình của bạn và truy cập mọi lúc',
  signUpDesc: 'Tạo tài khoản miễn phí để lưu và quản lý hành trình',
  emailLabel: 'Email',
  passwordLabel: 'Mật khẩu',
  passwordHint: '(tối thiểu 6 ký tự)',
  displayNameLabel: 'Tên hiển thị',
  displayNamePlaceholder: 'Tên của bạn',
  processingBtn: 'Đang xử lý…',
  signInBtn: 'Đăng nhập',
  createAccountBtn: 'Tạo tài khoản',
  noAccount: 'Chưa có tài khoản? Tạo ngay',
  alreadyAccount: 'Đã có tài khoản? Đăng nhập',
  continueWithout: 'Tiếp tục không đăng nhập',
  checkEmailTitle: 'Kiểm tra email của bạn',
  checkEmailDesc: (email) =>
    `Chúng tôi đã gửi link xác nhận đến ${email}. Nhấn vào link để kích hoạt tài khoản rồi đăng nhập lại.`,
  closeBtn: 'Đóng',
  passwordTab: 'Mật khẩu',
  magicLinkTab: 'Magic Link',
  sendMagicLinkBtn: 'Gửi magic link',
  signInWithGoogle: 'Đăng nhập với Google',

  /* ── Home ────────────────────────── */
  yourItineraries: 'Hành trình của bạn',
  welcomeBack: 'Chào mừng trở lại',
  welcomeUser: (name) => `Chào mừng trở lại, ${name}!`,
  tripsCount: (n) => `${n} hành trình đã lưu`,
  happeningToday: (n) => `${n} đang diễn ra hôm nay`,
  upcomingCount: (n) => `${n} sắp tới`,
  createNewItinerary: 'Tạo hành trình mới',
  imoveRoute: 'Tuyến IMOVE',
  liveToday: 'Đang chạy hôm nay',
  readyLabel: 'Sẵn sàng',
  nextItinerary: 'Hành trình kế tiếp',
  singaporePlanner: 'Bộ lập kế hoạch Singapore',
  homeStatTrips: 'Hành trình',
  homeStatToday: 'Hôm nay',
  homeStatUpcoming: 'Sắp tới',
  travelWorkspace: 'Không gian hành trình',
  travelWorkspaceDesc: 'Lên kế hoạch, mở lại và tiếp tục các hành trình IMOVE đã lưu.',
  previewLabel: 'Xem trước',
  previewMeta: '3 ngày · 8 điểm · sẵn sàng di chuyển',
  routePointAirport: 'Sân bay',
  routePointMrt: 'Tuyến MRT xanh',
  routePointMarina: 'Marina Bay',
  landingHeroEyebrow: 'Lập kế hoạch giao thông công cộng Singapore',
  landingHeroLine1: 'Transit Planning Made',
  landingHeroEasy: 'Easy',
  landingHeroDesc:
    'IMOVE giúp du khách lần đầu đến Singapore biến danh sách địa điểm thành lịch trình theo ngày với MRT, xe buýt, thời gian đi bộ, chi phí và hỗ trợ khi có gián đoạn.',
  landingHeroCta: 'Bắt đầu lập kế hoạch',
  landingHeroStatLive: 'kiểm tra transit trực tiếp',
  landingHeroStatAgents: 'agent lập kế hoạch',
  landingHeroStatFake: 'lộ trình ước đoán',
  landingSavedEyebrow: 'Không gian của bạn',
  landingSavedTitle: 'Tiếp tục các hành trình đã lưu',
  landingInnovativeEyebrow: 'Lập kế hoạch transit thông minh',
  landingInnovativeTitle: 'Dành cho du khách cần nhiều hơn một bản đồ tĩnh',
  landingFeatureRoutingTitle: 'Tuyến MRT và xe buýt xác thực',
  landingFeatureRoutingDesc:
    'Mỗi chặng được lập bằng dữ liệu định tuyến giao thông công cộng thật, không tự đoán thời gian.',
  landingFeatureAlertsTitle: 'Nhận biết gián đoạn realtime',
  landingFeatureAlertsDesc:
    'IMOVE theo dõi MRT, xe buýt, thời tiết và sự cố dịch vụ có thể ảnh hưởng lịch trình trong ngày.',
  landingFeatureAgentsTitle: 'Lập kế hoạch đa tác nhân thích nghi',
  landingFeatureAgentsDesc:
    'Planning, adaptation và memory agents phối hợp để gợi ý thay đổi tuyến thực tế hơn.',
  landingStepsEyebrow: 'Tạo lịch trình trong 3 bước',
  landingStepsTitle: 'Tạo lịch trình Singapore biết sẵn bạn sẽ di chuyển thế nào',
  landingStepPlacesTitle: 'Chọn địa điểm',
  landingStepPlacesDesc:
    'Thêm điểm tham quan, ăn uống và khu vực bạn muốn ghé trong một hoặc nhiều ngày.',
  landingStepPlanTitle: 'Tạo ngày có tính đến di chuyển',
  landingStepPlanDesc:
    'IMOVE sắp xếp điểm dừng và gắn MRT, bus, thời gian đi bộ, chi phí và chi tiết tuyến cho từng chặng.',
  landingStepAdaptTitle: 'Đi và thích nghi',
  landingStepAdaptDesc:
    'Khi có trễ tuyến, đổi thời tiết hoặc vấn đề lộ trình, app có thể đề xuất phương án thay thế.',
  landingServicesEyebrow: 'Dịch vụ nổi bật của IMOVE',
  landingServicesTitle: 'Hỗ trợ giao thông công cộng từ lúc lập kế hoạch đến ngày đi',
  landingServiceRail: 'Tuyến rail',
  landingServiceBus: 'Lựa chọn bus',
  landingServiceLive: 'Cảnh báo chủ động',
  landingServiceVerified: 'Không fallback bịa',
  landingDiscoverEyebrow: 'Khám phá tính năng',
  landingDiscoverTitle: 'Thiết kế xoay quanh thực tế transit tại Singapore',
  landingDiscoverMapTitle: 'Lịch trình gắn với bản đồ',
  landingDiscoverMapDesc:
    'Xem từng ngày cùng đường tuyến, điểm dừng và marker phương tiện.',
  landingDiscoverWeatherTitle: 'Đổi kế hoạch theo thời tiết',
  landingDiscoverWeatherDesc:
    'Lịch trình nhiều hoạt động ngoài trời có thể được điều chỉnh khi dự báo thay đổi.',
  landingDiscoverBudgetTitle: 'Ngữ cảnh chi phí và đi bộ',
  landingDiscoverBudgetDesc:
    'Xem chi phí, thời gian hoạt động và quãng đi bộ trước khi chọn tuyến.',
  landingDiscoverMemoryTitle: 'Học từ phản hồi',
  landingDiscoverMemoryDesc:
    'Phản hồi đã lưu giúp các kế hoạch sau khớp hơn với sở thích di chuyển của bạn.',
  landingReadyEyebrow: 'Sẵn sàng cho kế hoạch Singapore',
  landingReadyTitle: 'Tự tin di chuyển dù chưa quen MRT, bus hoặc địa lý Singapore',
  landingReadyDesc:
    'Bắt đầu từ những địa điểm bạn quan tâm. IMOVE biến chúng thành lịch trình ưu tiên di chuyển và giữ kế hoạch linh hoạt khi thực tế thay đổi.',
  landingReadyCardTitle: 'Phù hợp solo và nhóm nhỏ',
  landingReadyCardDesc:
    'Tốt nhất cho du khách lần đầu đến Singapore hoặc bất kỳ ai muốn có kế hoạch transit rõ ràng hơn.',
  landingFooterDesc:
    'IMOVE là travel planner ưu tiên giao thông công cộng tại Singapore, kết hợp lập lịch trình với thích nghi realtime.',
  landingFooterExplore: 'Khám phá',
  landingFooterPlanner: 'Planner',
  landingFooterTrips: 'Hành trình đã lưu',
  landingFooterAlerts: 'Cảnh báo transit',
  landingFooterSupport: 'Hỗ trợ',
  landingFooterContact: 'Liên hệ',
  landingFooterMessage: 'Gửi tin nhắn',
  landingContactName: 'Tên',
  landingContactEmail: 'Email',
  landingContactMessage: 'Bạn cần hỗ trợ gì?',
  landingContactSend: 'Gửi',
  filter_All: 'Tất cả',
  filter_Today: 'Hôm nay',
  filter_Upcoming: 'Sắp tới',
  filter_Drafts: 'Nháp',
  filter_Past: 'Đã qua',
  noTripsTitle: 'Lên kế hoạch khám phá Singapore',
  noTripsDesc:
    'Tạo chuyến đi đầu tiên với tuyến MRT và xe buýt thực tế, lịch trình theo giờ và gợi ý từ AI.',
  startPlanning: 'Bắt đầu lên kế hoạch',
  planNewTrip: 'Tạo chuyến đi mới',
  freshItinerary: 'Bắt đầu lịch trình mới',
  openBtn: 'Mở',
  startTripBtn: 'Bắt đầu',
  liveLabel: 'Trực tiếp',
  startsTodayTitle: 'Chuyến đi Singapore của bạn bắt đầu hôm nay!',
  startsTodayDesc: 'Sẵn sàng khám phá? Chúng tôi sẽ dẫn đường qua từng điểm trong lịch trình.',
  laterBtn: 'Để sau',
  readyToNavigate: 'Bắt đầu điều hướng',
  noTripsCategory: 'Chưa có hành trình nào trong danh mục này.',
  dest: 'Điểm đến',
  savedLabel: 'Đã lưu',
  daysUnit: (n) => `${n} ngày`,
  stopsUnit: (n) => `${n} điểm`,

  /* ── Planner — mode chooser ────────── */
  planYourTrip: 'Lên kế hoạch đến Singapore',
  choosePlanMethod: 'Chọn cách bạn muốn tạo hành trình',
  buildYourselfTitle: 'Tự tạo hành trình',
  buildYourselfDesc:
    'Tự chọn từng địa điểm — hệ thống gợi ý phương tiện di chuyển và bạn có thể tuỳ chỉnh theo ý muốn.',
  recommendedBadge: 'Đề xuất',
  tag_freeChoice: 'Tự do lựa chọn',
  tag_transport: 'Gợi ý phương tiện',
  tag_customizable: 'Tuỳ chỉnh được',
  planWithAITitle: 'Lên kế hoạch bằng AI',
  planWithAIDesc: 'Nhập sở thích và để AI gợi ý lịch trình. Phù hợp khi chưa biết ghé đâu.',
  changeMethod: 'Thay đổi phương thức',

  /* ── Planner — manual ──────────────── */
  manualHeaderLabel: 'Tự tạo hành trình',
  manualHeaderSub: 'Thêm địa điểm và chọn phương tiện di chuyển',
  tripInfoSection: 'Thông tin chuyến đi',
  tripNameLabel: 'Tên chuyến đi',
  tripNamePlaceholder: 'Ví dụ: Singapore 4 ngày 3 đêm',
  flexibleLabel: 'Linh hoạt',
  specificDatesLabel: 'Ngày cụ thể',
  flexibleHint: 'Ngày linh hoạt — có thể đặt sau từ trang chuyến đi.',
  numDaysLabel: 'Số ngày',
  placesSection: (n) => `Địa điểm (${n})`,
  clickToChange: 'Nhấn chip phương tiện để thay đổi',
  noPlacesTitle: 'Chưa có địa điểm nào',
  noPlacesHint: 'Nhấn "Thêm địa điểm" bên dưới để bắt đầu',
  addPlaceBtn: 'Thêm địa điểm',
  searchPlaceTitle: 'Tìm & thêm địa điểm',
  createTripBtn: (n) => `Tạo hành trình (${n} địa điểm)`,
  addAtLeastOne: 'Thêm ít nhất 1 địa điểm để tiếp tục',
  creatingTrip: 'Đang tạo hành trình…',

  /* ── Planner — AI ──────────────────── */
  aiHeaderLabel: 'Lập kế hoạch AI',
  aiHeaderSub: 'AI sẽ gợi ý lịch trình dựa trên sở thích của bạn',
  whenGoingLabel: 'Khi nào bạn đi?',
  flexibleDatesHint: 'Ngày linh hoạt — có thể đặt sau từ trang chuyến đi.',
  preferencesLabel: 'Sở thích',
  travellingWithLabel: 'Đi cùng ai',
  travelStyleLabel: 'Phong cách du lịch',
  tripPaceLabel: 'Nhịp độ chuyến đi',
  aiHint:
    'AI sẽ chọn địa điểm phù hợp nhất dựa trên phong cách và nhịp độ của bạn, rồi tạo lịch trình theo từng ngày với tuyến MRT và xe buýt thực tế.',
  planWithAIBtn: 'Lập kế hoạch bằng AI',
  planningBtn: 'Đang lên kế hoạch…',
  selectStartDate: 'Vui lòng chọn ngày khởi hành',

  /* ── Planner — confirm step ────────── */
  planReady: 'Kế hoạch sẵn sàng!',
  saveItinerary: 'Lưu hành trình của bạn?',
  startOver: 'Làm lại',
  saveAndView: 'Lưu & Xem lịch trình',

  /* ── Place search ──────────────────── */
  popularPlaces: 'Địa điểm nổi tiếng tại Singapore',
  searchPlaceholder: 'Tìm địa điểm tại Singapore…',
  addedBtn: 'Đã thêm',
  addBtn: 'Thêm',
  limitedData: 'Thiếu dữ liệu',
  noResults: (q) => `Không tìm thấy kết quả cho "${q}"`,
  loadingPlaces: 'Đang tải địa điểm…',
  statusToday: 'Đang diễn ra',
  or: 'hoặc',
  flexibleDates: 'Ngày linh hoạt',

  /* ── Transport ─────────────────────── */
  transport_walk: 'Đi bộ',
  transport_bus: 'Xe buýt',
  transport_mrt: 'MRT',

  /* ── Alert Banner ────────────────── */
  alertTransit: 'Cảnh báo giao thông',
  alertWeather: 'Cảnh báo thời tiết',
  alertService: 'Dịch vụ không khả dụng',
  alertPreview: 'Cập nhật kế hoạch',
  alertAccept: 'Chấp nhận',
  alertAcceptSwap: 'Cập nhật kế hoạch',
  alertDismiss: 'Bỏ qua',
  alertGotIt: 'Đã hiểu',
  alertUpdating: 'Đang cập nhật...',
  alertApplying: 'Đang áp dụng...',
  alertDiscard: 'Bỏ qua',
  alertPreviewExpired: 'Bản xem trước đã hết hiệu lực. Hãy xem trước lại để tính toán phương án mới.',
  alertHelpful: 'Có ích',
  alertNotHelpful: 'Không có ích',
  alertFeedbackSent: 'Đã gửi phản hồi',
  alertFeedbackLoginRequired: 'Đăng nhập để gửi phản hồi cho chuyến đi này.',
  alertFeedbackFailed: 'Không gửi được phản hồi. Vui lòng thử lại.',
  alertRain: 'Mưa',
  alertChance: (pct) => `${pct}% cơ hội`,
  alertOutdoorAffected: (count) => `· ảnh hưởng ${count} điểm ngoài trời`,
  alertOutdoorFallback: 'Thời tiết có thể ảnh hưởng điểm ngoài trời',
  alertNoSwapsNeeded: 'Không cần thay đổi — tất cả các điểm đều thân thiện trong nhà.',

  /* ── Closing-risk alert (dev20) ───── */
  alertSchedule: 'Trễ giờ',
  crHeader: (place, closeTime, arrival, deficit) =>
    `${place} đóng cửa lúc ${closeTime} — bạn dự kiến tới ${arrival} (trễ ~${deficit}p).`,
  crLeaveEarlier: 'Rời sớm hơn',
  crLeaveEarlierAdvice: (place, time, mins) =>
    `Rời ${place} trước ${time} (sớm hơn ~${mins}p) là vẫn kịp.`,
  crSkip: 'Bỏ điểm này',
  crPush: 'Đẩy sang ngày khác',
  crChooseDay: 'Chọn ngày:',
  crDayLabel: (day) => `Ngày ${day}`,
  crBadgeRoom: (mins) => `còn ~${Math.round((mins / 60) * 10) / 10}h`,
  crBadgeFull: 'Đã đầy',
  crBadgeClosed: (weekday) => `Đóng cửa ${weekday}`,
  crPushClosedAll: (place) =>
    `Không thể dời sang ngày khác — ${place} đóng cửa vào tất cả các ngày còn lại của chuyến đi.`,
  crPushNoOtherDay: 'Không thể dời — đây là ngày cuối, không còn ngày nào khác.',
  crRecommended: 'Nên dùng',
  crConfirm: 'Xác nhận',

  /* ── Trip page ───────────────────── */
  tripDefaultName: 'Chuyến đi Singapore',
  tripDaysCount: (n) => `${n} ngày`,
  tripPlacesCount: (n) => `${n} địa điểm`,
  tripStopsCount: (n) => `${n} điểm`,
  tripLive: 'Trực tiếp',
  tripPaused: 'Tạm dừng',
  tripOverview: 'Tổng quan',
  tripSummary: 'Tóm tắt',
  tripDay: (n) => `Ngày ${n}`,
  tripAddDay: 'Thêm ngày',
  tripRemoveDay: 'Xoá ngày',
  tripEditSetup: 'Chỉnh thiết lập',
  tripResumeTrip: 'Tiếp tục chuyến đi',
  tripUpdateRoutesFirst: 'Cập nhật lộ trình trước',
  tripGoodToGo: 'Sẵn sàng',
  tripEstimated: 'Ước tính',
  tripBannerLive: (day) => `Trực tiếp · Ngày ${day} — chạm "Đã đến" khi bạn tới mỗi điểm.`,
  tripBannerEdit: 'Chế độ chỉnh sửa — chuyến đi đang tạm dừng. Tiếp tục khi sẵn sàng.',
  tripBannerPlanning: 'Chế độ lập kế hoạch — xem lại lịch trình trước khi bắt đầu.',
  tripGpsOff: 'Không có GPS — tự báo đến đã tắt. Hãy chạm "Đã đến" thủ công ở mỗi điểm.',
  tripStartsToday: 'Chuyến đi của bạn bắt đầu hôm nay! Vào bảng điều khiển để bắt đầu.',
  tripOffline: 'Chế độ ngoại tuyến — đang hiển thị lịch trình đã lưu.',
  tripRainMore: (n) => `Dự báo mưa cho ${n} ngày nữa`,
  tripLoadError: (msg) => `Không tải được chuyến đi: ${msg}`,
  tripUnavailableTitle: 'Không mở được chuyến đi',
  tripUnavailableBody: () => 'Chuyến đi này có thể là riêng tư, đã bị xoá, hoặc bạn không có quyền xem.',
  tripNotFound: 'Không tìm thấy chuyến đi',
  tripAccessDenied: 'Bạn không có quyền truy cập chuyến đi này.',
  tripLoginRequired: 'Vui lòng đăng nhập lại để xem chuyến đi này.',
  tripBackHome: 'Về trang chủ',
  tripStartNew: 'Tạo chuyến đi mới',
  tripOverviewDesc: 'Xem cảnh báo, khoảng thời gian trống và cấu trúc lộ trình mỗi ngày.',
  tripUpdateRoute: 'Cập nhật lộ trình',
  tripKeepOrder: 'Giữ thứ tự của tôi',
  tripKeepOrderDesc: 'Thời gian di chuyển thật, giữ nguyên thứ tự điểm',
  tripLetAIOptimise: 'Để AI tối ưu',
  tripLetAIOptimiseDesc: 'AI sắp xếp lại để hiệu quả nhất',
  tripOptimiseOrder: 'Tối ưu thứ tự',
  tripStartTrip: 'Bắt đầu chuyến đi',
  tripLongCommutes: 'Chặng di chuyển dài',
  tripDayDesc: 'Thẻ địa điểm và lộ trình kèm chi tiết phương tiện.',
  tripNoLegs: 'Ngày này chưa có lộ trình',
  tripLongTransits: (n) => `${n} chặng dài hôm nay`,
  tripTransit: 'di chuyển',
  tripAddPlace: 'Thêm địa điểm',
  tripRemove: 'Xoá',
  tripRemovePlace: 'Xoá địa điểm',
  tripHotel: 'Khách sạn',
  tripReturnHotel: 'Về khách sạn',
  tripUp: 'Lên',
  tripDown: 'Xuống',
  tripEmptyDay: 'Ngày trống',
  tripEstimatedHint: 'Ước tính — chạm "Cập nhật lộ trình" để có thời gian di chuyển thật.',
  tripDestination: 'Điểm đến',
  tripStartingFrom: 'Xuất phát từ',
  tripMinVisit: (n) => `tham quan ${n} phút`,
  tripCategoryFallback: 'địa điểm',
  tripMinShort: (n) => `${n} phút`,
  tripClosed: (days) => `Đóng cửa ${days}`,
  tripBestTime: (s, e) => `Tốt nhất ${s}–${e}`,
  tripOrigin: 'Điểm xuất phát',
  tripRoute: (from, to) => `${from} → ${to}`,
  tripOpenGrab: 'Mở Grab',
  tripChange: 'Đổi',
  tripComparing: 'Đang so sánh…',
  tripCompareModes: 'So sánh phương tiện',
  tripTransitDetails: 'Chi tiết di chuyển',
  tripUnavailable: 'Không khả dụng',
  tripBusLabel: (route, name) => `Buýt ${route}${name ? ` — ${name}` : ''}`,
  tripYourLocation: 'Vị trí của bạn',
  tripGrabOpened: (from, to) => `Đã mở Grab — đón: ${from}, trả: ${to}`,
  tripGrabNotFound: (from, to) => `Không tìm thấy app Grab — đã mở Google Maps (${from} → ${to})`,
  tripActiveLeg: 'Chặng hiện tại',
  tripLegProgress: (day, i, total) => `Ngày ${day} · Chặng ${i}/${total}`,
  tripBack: 'Quay lại',
  tripGoBackTitle: 'Quay lại chặng trước',
  tripContinue: 'Tiếp tục',
  tripArrived: 'Đã đến',
  tripDeleteConfirm: 'Xoá vĩnh viễn chuyến đi này?',
  // dev28 — shared confirm dialog + date/time picker strings
  confirmDeleteTitle: 'Xoá chuyến đi?',
  confirmDeleteBtn: 'Xoá',
  cancelBtn: 'Huỷ',
  drpNoDates: 'Chưa chọn ngày',
  drpPickEnd: 'chọn ngày kết thúc',
  drpDayCount: (n) => `${n} ngày`,
  tripOptimiseTitle: 'Tối ưu thứ tự?',
  tripOptimiseDesc: 'AI sẽ sắp xếp lại các điểm để hiệu quả hơn bằng dữ liệu di chuyển thật. Thứ tự hiện tại có thể thay đổi.',
  tripCancel: 'Huỷ',
  tripConfirm: 'Xác nhận',
  tripMsgEstimatedLegs: (n) => `Chưa lấy được lộ trình thật cho ${n} chặng — hãy thử "Cập nhật lộ trình" lại sau giây lát.`,
  tripMsgDistributed: (n) => `Đã tối ưu lộ trình — phân bổ trên ${n} ngày.`,
  tripMsgReordered: (n) => `Đã tối ưu lộ trình! Sắp xếp lại ${n} điểm.`,
  tripMsgRoutesUpdated: 'Đã cập nhật lộ trình với thời gian di chuyển thật — lịch trình đã mở khoá.',
  tripMsgAlreadyOptimal: 'Đã tối ưu — không cần sắp xếp lại.',
  transport_cycle: 'Đạp xe',
  transport_grab: 'Grab',

  /* ── Summary tab ─────────────────── */
  sumSaveTitle: 'Lưu hành trình của bạn',
  sumSaveDesc: 'Xem lại các ngày và phương tiện ở trên, rồi lưu khi sẵn sàng.',
  sumTripName: 'Tên chuyến đi',
  sumSaveBtn: 'Lưu hành trình',
  sumTitle: 'Tóm tắt chuyến đi',
  sumDesc: 'Ước tính từ lịch trình hiện tại — sẽ tính lại khi bạn đổi phương tiện.',
  sumActiveTime: 'Thời gian hoạt động',
  sumTransitCost: 'Chi phí di chuyển',
  sumWalkDist: 'Quãng đi bộ',
  sumTransfers: 'Lần chuyển tuyến',
  sumByDay: 'Theo ngày',
  sumPaceCheck: 'Kiểm tra nhịp độ',
  sumPaceText: (stops, days, avg) => `Chuyến đi có ${stops} điểm trong ${days} ngày — trung bình ${avg} điểm/ngày. Khá thoải mái.`,
  sumAgentActivity: 'Hoạt động của agent',
  sumNoAgent: 'Chưa ghi nhận can thiệp nào từ agent.',
  sumShareExport: 'Chia sẻ & xuất',
  sumShareLink: 'Chia sẻ liên kết',
  sumSavePdf: 'Lưu PDF',
  sumDanger: 'Vùng nguy hiểm',
  sumDangerDesc: 'Xoá vĩnh viễn chuyến đi này khỏi cơ sở dữ liệu.',
  sumDeleteTrip: 'Xoá chuyến đi',

  /* ── Bus arrivals ────────────────── */
  busArr: 'Tới',
  busMin: (n) => `${n} phút`,
  busRoute: 'Tuyến',
  busArrivals: 'Giờ đến',
  busLoad: 'Mức tải',
  busLoadLow: 'Vắng',
  busLoadModerate: 'Vừa',
  busLoadHigh: 'Đông',
  busNoServices: 'Không có tuyến nào tại trạm này.',
  busRetry: 'Thử lại',
  busFailed: 'Không tải được giờ xe',
  busJustNow: 'vừa xong',
  busAgo: (s) => `${s}s trước`,
  busUpdated: (label) => `Cập nhật ${label}`,
  busRefresh: 'Làm mới giờ xe',

  /* ── Settings page ───────────────── */
  setEyebrow: 'Cài đặt',
  setTitle: 'Tuỳ chọn di chuyển',
  setDesc: 'IMOVE dùng các ưu tiên này khi chọn giữa MRT, xe buýt, đi bộ và đạp xe.',
  setWFasterLabel: 'Tuyến nhanh hơn',
  setWFasterDesc: 'Ưu tiên thời gian di chuyển ngắn',
  setWCostLabel: 'Giá vé rẻ hơn',
  setWCostDesc: 'Ưu tiên phương tiện rẻ hơn',
  setWWalkLabel: 'Ít đi bộ hơn',
  setWWalkDesc: 'Giảm quãng đường đi bộ',
  setWTransferLabel: 'Ít chuyển tuyến hơn',
  setWTransferDesc: 'Tránh lộ trình phức tạp',
  lvlLow: 'Thấp',
  lvlMed: 'Trung bình',
  lvlHigh: 'Cao',
  setSignInTitle: 'Đăng nhập để cá nhân hoá hành trình',
  setBullet1: 'Mang theo kế hoạch của bạn trên mọi thiết bị.',
  setBullet2: 'Khám phá lộ trình phù hợp với nhịp độ và hồ sơ của bạn.',
  setBullet3: 'Trò chuyện với trợ lý thông minh giúp lập và điều chỉnh chuyến đi dễ dàng.',
  setBullet4: 'Để “Tuỳ chọn của tôi” dẫn lối cho bạn khi lập kế hoạch.',
  setRoutingPriorities: 'Ưu tiên định tuyến',
  setHowItWorks: 'Cách hoạt động',
  setHowItWorksDesc: 'Mức cao hơn sẽ ưu tiên yếu tố đó mạnh hơn. Các mức được cân bằng tự động khi bạn lưu.',
  setReset: 'Đặt lại',
  setSave: 'Lưu',
  setSaved: 'Đã lưu tuỳ chọn.',

  /* ── Home dashboard ──────────────── */
  homeBadge: 'Bảng điều khiển IMOVE',
  homeHeroTitle: 'Lập kế hoạch, theo dõi và điều chỉnh chuyến đi Singapore.',
  homeHeroDesc: 'Quản lý hành trình đã lưu, bắt đầu chuyến trực tiếp và kiểm tra LTA/thời tiết trước khi khởi hành.',
  homeHeroCarouselTitle: 'Khám phá Singapore với một kế hoạch luôn theo kịp bạn.',
  homeHeroCarouselDesc: 'Xây dựng hành trình chỉn chu, so sánh lựa chọn di chuyển và điều chỉnh lộ trình theo nhịp sống Singapore.',
  homeHeroCta: 'Lên chuyến đi mới',
  homeHeroSecondaryCta: 'Thiết lập tuỳ chọn',
  homeFeature1Title: 'Kế hoạch vừa vặn với bạn',
  homeFeature1Desc: 'Cân bằng thời gian, chi phí, đi bộ và số lần chuyển tuyến.',
  homeFeature2Title: 'Dựng từng ngày',
  homeFeature2Desc: 'Biến các điểm đến Singapore thành lộ trình khả thi.',
  homeFeature3Title: 'Điều chỉnh khi đang đi',
  homeFeature3Desc: 'Luôn sẵn sàng trước thay đổi giao thông và thời tiết.',
  homePreferences: 'Tuỳ chọn',
  homeLive: 'Trực tiếp',
  homeLtaWeather: 'LTA/thời tiết',
  homeOpenAlerts: 'Cảnh báo đang mở',
  homeStatusToday: 'Hôm nay',
  homeStatusUpcoming: 'Sắp tới',
  homeStatusDraft: 'Nháp',
  homeStatusPast: 'Đã qua',
  homeStartsTodaySuffix: 'bắt đầu hôm nay',
  homeStart: 'Bắt đầu',
  homeDays: 'Số ngày',
  homeStops: 'Điểm dừng',
  homeAlerts: 'Cảnh báo',
  homeDeleteTitle: 'Xoá chuyến đi',
  homeDeleteConfirm: (name) => `Xoá "${name}"?`,
  homeSearch: 'Tìm hành trình đã lưu',
  homeNoTrips: 'Chưa có chuyến đi nào',
  homeNoTripsDesc: 'Tạo hành trình mới hoặc đổi bộ lọc.',

  /* ── Planner wizard ──────────────── */
  plnBackHome: 'Huỷ và về trang chủ',
  plnEyebrow: 'Trình tạo hành trình',
  plnTitle: 'Thiết lập chuyến đi Singapore',
  plnStep1: 'Cơ bản',
  plnStep2: 'Khách sạn',
  plnStep3: 'Phong cách',
  plnStep4: 'Tham quan',
  plnGeneralSettings: 'Thiết lập chung',
  plnGeneralDesc: 'Cung cấp thông tin cơ bản để dựng lịch trình.',
  plnTripName: 'Tên chuyến đi',
  plnBudget: 'Ngân sách di chuyển (SGD)',
  plnDays: 'Số ngày',
  plnDatesMode: 'Chế độ ngày',
  plnFlexible: 'Linh hoạt',
  plnCalendar: 'Theo lịch',
  plnStartDate: 'Ngày bắt đầu',
  plnDailyStart: 'Giờ bắt đầu mỗi ngày',
  plnAutoOptimize: 'Tự tối ưu thứ tự',
  plnAutoOptimizeDesc: 'Tự sắp xếp lại các điểm để tiết kiệm thời gian di chuyển.',
  plnHotelTitle: 'Nơi lưu trú',
  plnOptional: 'Tuỳ chọn',
  plnHotelDesc: 'Cho biết nơi bạn ở. Mỗi ngày lộ trình sẽ bắt đầu trực tiếp từ khách sạn của bạn.',
  plnHotelSearch: 'Tìm khách sạn',
  plnHotelPlaceholder: 'VD: Marina Bay Sands, Orchard Hotel',
  plnUse: 'Chọn',
  plnHotelNotFound: 'Không tìm thấy địa điểm. Hãy thử tên cụ thể hơn.',
  plnTransitWeights: 'Trọng số di chuyển',
  plnTransitDesc: 'Chọn hồ sơ du lịch để tinh chỉnh cách xếp hạng phương tiện.',
  plnFastest: 'Nhanh nhất',
  plnFastestDesc: 'Giảm tối đa thời gian di chuyển. Ưu tiên tuyến MRT tốc độ cao.',
  plnCheapest: 'Rẻ nhất',
  plnCheapestDesc: 'Giảm tối đa chi phí. Ưu tiên xe buýt nội đô và đoạn đi bộ.',
  plnLeastWalking: 'Ít đi bộ',
  plnLeastWalkingDesc: 'Hạn chế đi bộ. Chọn tuyến tận nơi.',
  plnLeastTransfers: 'Ít chuyển tuyến',
  plnLeastTransfersDesc: 'Tránh đổi tuyến. Ưu tiên đi thẳng một lần.',
  plnUseProfile: 'Dùng hồ sơ tuỳ chọn của tôi',
  plnUseProfileDesc: 'Tự động tải trọng số cá nhân hoá đã cấu hình trong cài đặt tài khoản.',
  plnWeightsAlloc: 'Phân bổ trọng số',
  plnLoadsProfile: 'Tải giá trị hồ sơ tài khoản từ cơ sở dữ liệu',
  plnDimDuration: 'Thời gian di chuyển',
  plnDimCost: 'Chi phí vé',
  plnDimWalking: 'Số phút đi bộ',
  plnDimTransfers: 'Số lần chuyển tuyến',
  plnAttractions: 'Điểm tham quan Singapore',
  plnStep4of4: 'Bước 4/4',
  plnPickSights: 'Chọn điểm tham quan. Cần ít nhất 2 địa điểm từ danh sách tuyển chọn.',
  plnCuratedSearch: 'Tìm địa điểm tuyển chọn',
  plnSelectedShortlist: (n) => `Đã chọn (${n})`,
  plnGenerating: 'Đang tạo',
  plnGeneratePlan: 'Tạo',
  plnNextIdle: 'Tiếp',
  plnNext: 'Qua',
  plnConfigSummary: 'Tóm tắt thiết lập',
  plnDuration: 'Thời lượng',
  plnSumBudget: 'Ngân sách di chuyển',
  plnHotelStart: 'Điểm xuất phát',
  plnTravelStyle: 'Phong cách',
  plnStopsSelected: 'Số điểm đã chọn',
  plnNotSet: 'Chưa đặt',
  plnStartsFirstStop: 'Bắt đầu từ điểm đầu tiên',
  plnMin2Places: 'Vui lòng chọn ít nhất 2 địa điểm trước khi tạo lịch trình.',
  plnBackToTop: 'Lên đầu trang',
  plnNoSelected: 'Chưa chọn địa điểm nào',
  plnNoSelectedDesc: 'Chọn địa điểm ở bên trái để thêm vào chuyến đi.',
  plnDaysValue: (n) => `${n} ngày`,
  plnStopsValue: (n) => `${n} điểm`,

  /* ── DayPlan ─────────────────────── */
  dpNoStopsYet: 'Chưa có điểm dừng',
  dpDragReorder: 'Kéo để sắp xếp lại',
  dpNoPlaces: 'Chưa có địa điểm',
  dpNoPlacesDesc: 'Quay lại và thêm địa điểm vào lịch trình.',
  dpAddPlaceToDay: (day) => `Thêm địa điểm vào Ngày ${day}`,
  dpDayNotes: 'Ghi chú trong ngày',
  dpDayNotesPlaceholder: 'Mang áo khoác mỏng, điểm rút tiền, đặt bàn tối 8h…',

  /* ── Overview tab ────────────────── */
  ovOptimizing: 'Đang tối ưu…',
  ovOptimizeRoute: 'Tối ưu lộ trình',
  ovActive: 'Hoạt động',
  ovTransit: 'Di chuyển',
  ovWalk: 'Đi bộ',
  ovStops: 'Điểm',
  ovViewMap: 'Xem trên bản đồ',
  ovNotices: 'Lưu ý',
  ovEmptyTap: 'Trống — chạm để lên kế hoạch',

  /* ── Active leg focus ────────────── */
  alStopsCompleted: (n) => `Đã xong ${n} điểm`,
  alStopsUpNext: (n) => `${n} điểm tiếp theo`,
  alRainExpected: (name) => `Dự báo mưa lớn tại ${name}`,
  alSwapToPre: 'Đổi sang ',
  alSwapToPost: ' (trong nhà)?',
  alApproveSwap: 'Đồng ý đổi ▶',
  alNoRoute: 'Chưa có lộ trình',
  alGetToStart: 'ĐẾN ĐIỂM XUẤT PHÁT',
  alArrivedAt: (name) => `Đã đến ${name}`,
  alToFirstStop: 'đến điểm đầu',
  alYouAreHere: 'BẠN ĐANG Ở ĐÂY',
  alNear: (name) => `· gần ${name}`,
  alAcquiringGps: 'Đang lấy vị trí GPS…',
  alDistTo: (dist, name) => `${dist} đến ${name}`,
  alOpenRange: (s, e) => `Mở cửa · ${s} – ${e}`,
  alOutdoor: 'Ngoài trời',
  alMinVisit: (n) => `~${n} phút tham quan`,
  alNotePlaceholder: 'Thêm ghi chú cho điểm này…',
  alArrivedExcl: 'Đã đến!',
  alArrivedDest: 'Đã đến nơi',

  /* ── Transit segment ─────────────── */
  tsChooseMode: 'Chọn phương tiện di chuyển',
  tsTransit: 'Công cộng',
  tsWalking: 'Đi bộ',
  tsCycling: 'Đạp xe',
  tsNoRoute: 'Không có tuyến công cộng cho chặng này.',
  tsTaxiGrab: 'Taxi · Grab',
  tsOpenGrab: 'Mở app Grab ↗',
  tsStraightLine: 'Khoảng cách đường chim bay',

  /* ── Citymapper transit card ─────── */
  ctLrt: 'LRT',
  ctDriveTaxi: 'Lái xe / Taxi',
  ctCrowdLow: 'Thấp',
  ctCrowdModerate: 'Vừa',
  ctWalkTo: (name, mins) => `Đi bộ đến ${name}${mins ? ` (${mins} phút)` : ''}`,
  ctWalk: (mins) => `Đi bộ${mins ? ` (${mins} phút)` : ''}`,
  ctBoardAt: (name) => `Lên tại ${name}`,
  ctBoard: 'Lên xe',
  ctAlightAt: (name) => ` → Xuống tại ${name}`,
  ctDur: (mins, stops) => ` (${mins} phút${stops ? `, ${stops} trạm` : ''})`,
  ctHide: 'Ẩn',
  ctLiveArrivals: 'Giờ đến trực tiếp',
  ctEstimatedNote: '~ Thời gian ước tính dựa trên thời lượng tuyến điển hình',
  ctLiveAlert: 'Cảnh báo trực tiếp · Lỗi tín hiệu',
  ctDelayMsg: 'Trễ tới 15 phút giữa Somerset và Bugis',
  ctAltRoute: 'Có tuyến thay thế',
  ctApproxMin: (n) => `~${n} phút`,
  ctSaveMin: (n) => `Tiết kiệm ~${n} phút`,
  ctSwitchBus: 'Chuyển sang tuyến buýt ▶',
  ctDisrupted: 'GIÁN ĐOẠN',
  ctEst: '~ước tính',
  ctEditMode: 'Đổi phương tiện',

  /* ── Route card ──────────────────── */
  rcChangeMode: 'Đổi phương tiện di chuyển',
  rcNewMode: 'Phương tiện mới',
  rcSaving: 'Đang lưu...',

  /* ── Travel tips ─────────────────── */
  ttHeader: (n) => `Lưu ý hành trình (${n})`,
  ttAlways1: 'Mua thẻ EZ-Link tại Changi Airport hoặc 7-Eleven để đi MRT/bus — tiện hơn trả tiền mặt.',
  ttAlways2: 'Hầu hết hawker centre và quán ăn vỉa hè chỉ nhận tiền mặt SGD — mang theo tiền lẻ.',
  ttOutdoor: 'Mang kem chống nắng SPF 50+ — Singapore có UV Index cao quanh năm.',
  ttReligious: 'Ăn mặc kín đáo và cởi giày trước khi vào đền chùa hoặc nhà thờ Hồi giáo.',
  ttNight: 'Book vé trước trực tuyến để tránh xếp hàng tại các điểm tham quan về đêm.',
  ttNature: 'Kiểm tra dự báo thời tiết — mưa chiều thường xuyên từ tháng 11 đến tháng 1.',

  /* ── Place card ──────────────────── */
  pcOpen24h: 'Mở cửa 24h',
  pcOpenHours: (s) => `Mở cửa ${s}`,
  pcOutdoor: 'Ngoài trời',
  pcBestTime: (label) => `Thời điểm tốt nhất: ${label}`,
  pcNotes: 'Ghi chú',
  pcNotesPlaceholder: 'Thêm ghi chú — đặt vé trước, mang áo khoác, v.v.',

  /* ── Trip setup modal ────────────── */
  tsmTitle: 'Tuỳ chọn chuyến đi',
  tsmDesc: 'Điều chỉnh tên chuyến đi, ngày, ngân sách, khách sạn và giờ bắt đầu mỗi ngày. Các địa điểm hiện có được giữ nguyên.',
  tsmOriginPlaceholder: 'TP. Hồ Chí Minh',
  tsmDates: 'Ngày',
  tsmFlexibleDuration: 'Thời lượng linh hoạt',
  tsmStart: 'Bắt đầu',
  tsmEnd: 'Kết thúc',
  tsmDays: 'ngày',
  tsmDailyStart: 'Giờ bắt đầu mỗi ngày',
  tsmEachDay: 'mỗi ngày',
  tsmHotel: 'Khách sạn',
  tsmHotelOptional: '(tuỳ chọn — điểm xuất phát mỗi ngày)',
  tsmHotelPlaceholder: 'VD: Marina Bay Sands',
  tsmDateWarning: 'Đổi ngày, ngân sách, khách sạn hoặc giờ bắt đầu sẽ chạy lại việc lập lộ trình. Các địa điểm được giữ; các chặng sẽ được tính lại.',
  tsmSaveChanges: 'Lưu thay đổi',

  /* ── Trip map ────────────────────── */
  tmEstimated: '(ước tính)',
  tmCurrentLocation: 'Vị trí hiện tại của bạn',

  /* ── Chatbot ─────────────────────── */
  chatTitle: 'Trợ lý IMOVE',
  chatGreeting: 'Chào bạn! Hỏi mình gợi ý địa điểm hoặc nhờ chỉnh lịch trình — mình sẽ đề xuất để bạn xác nhận.',
  chatPlaceholder: 'Hỏi bất cứ điều gì về chuyến đi…',
  chatSend: 'Gửi',
  chatThinking: 'Đang xử lý…',
  chatOpen: 'Mở trợ lý',
  chatClose: 'Đóng trợ lý',
  chatProposalLabel: 'Đề xuất thay đổi',
  chatConfirm: 'Xác nhận',
  chatCancel: 'Huỷ',
  chatApplying: 'Đang áp dụng…',
  chatError: 'Đã có lỗi xảy ra. Vui lòng thử lại.',
  chatLoginRequired: 'Đăng nhập để sử dụng trợ lý',
  chatLoginHint: 'Trợ lý AI chỉ dành cho tài khoản đã đăng nhập.',
  chatUnread: (n) => `${n} cập nhật mới cho chuyến đi`,
  // dev25 P3 — rich chat blocks
  chatCardDuration: (n) => `${n} phút`,
  chatRouteCompare: 'Lựa chọn lộ trình',
  chatRouteFree: 'Miễn phí',
  chatMinShort: (n) => `${n} phút`,
  chatBusArrivals: (stop) => `Trạm xe buýt ${stop}`,
  chatBusNow: 'Sắp đến',
  chatBusEta: (n) => `${n} phút`,
  chatBusNone: 'Hiện chưa có chuyến nào',
}

export { EN, VI }
